In [5]:
import pandas as pd

df = pd.read_csv("data/emissions.csv")
#discard the first row as it was a test run
df = df[1:]

# add suffix to distinguish between quan and non-quant
suffix = "_quant"

# Add suffix to first and last entry in 'project_name'
df.loc[df.index[0], 'project_name'] += suffix  # First row
df.loc[df.index[-1], 'project_name'] += suffix  # Last row
df

,timestamp,project_name,run_id,duration,emissions,emissions_rate,cpu_power,gpu_power,ram_power,cpu_energy,...,cpu_count,cpu_model,gpu_count,gpu_model,longitude,latitude,ram_total_size,tracking_mode,on_cloud,pue
1,2025-01-27T18:10:20,meta-llama/Llama-3.1-8B-Instruct_quant,4279bef4-13d7-4aeb-81ef-4e0cf6c955da,1632.742385,0.034805,0.000021,42.5,325.684645,188.788404,0.019271,...,16,Intel(R) Xeon(R) Gold 5415+,1,1 x NVIDIA A100 80GB PCIe,12.2926,55.6514,503.435745,machine,N,1.0
2,2025-01-27T18:29:06,meta-llama/Llama-3.1-8B-Instruct,ee33aaee-7407-41d3-8ed2-c4cca3a9e70e,1086.632633,0.022709,0.000021,42.5,278.931486,188.788404,0.012825,...,16,Intel(R) Xeon(R) Gold 5415+,1,1 x NVIDIA A100 80GB PCIe,12.2926,55.6514,503.435745,machine,N,1.0
3,2025-01-27T18:43:38,meta-llama/Llama-3.2-3B-Instruct,98c17a06-cf17-4948-9496-51a4eca2ee86,827.685798,0.016706,0.000020,42.5,226.693260,188.788404,0.009768,...,16,Intel(R) Xeon(R) Gold 5415+,1,1 x NVIDIA A100 80GB PCIe,12.2926,55.6514,503.435745,machine,N,1.0
4,2025-01-27T19:03:21,meta-llama/Llama-3.2-3B-Instruct_quant,39c1722f-3a78-4a38-956f-f8ad11eeee46,1140.133013,0.023346,0.000020,42.5,204.922571,188.788404,0.013456,...,16,Intel(R) Xeon(R) Gold 5415+,1,1 x NVIDIA A100 80GB PCIe,12.2926,55.6514,503.435745,machine,N,1.0